services:

  web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
    container_name: gallery-web
    restart: always
    network_mode: "host"
    env_file:
      - .env.local

    volumes:
      - ./data:/app/data
      - ./public:/app/apps/web/public
